import Head from 'next/head';
import styled from 'styled-components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ontol Onboarding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Description>의료인 등록 밑에 설명 블라블라</Description>
        <InputForm>기본정보 및 밑에 입력 네모네모</InputForm>
      </main>
    </>
  );
}

const Description = styled.div`
  margin-top: 84px;
`;

const InputForm = styled.div``;
